<?php
return array(
	'warn'=>array(
		'title'=>'<span style="color:red;font-size:20px;">'.lang('alidayu_config_warn').'</span>',
		'type'=>'hidden',
		'value'=>''
	),
	'smsKey'=>array(
		'title'=>'<span style="color:#FF6666;">'.lang('alidayu_config_smskey').'<span>',
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'smsPass'=>array(
		'title'=>lang('alidayu_config_smspass'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'signature'=>array(
		'title'=>lang('alidayu_config_signature'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_REGISTER_VERFIY'=>array(
		'title'=>lang('alidayu_config_phone_user_register_verfiy'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_BIND'=>array(
		'title'=>lang('alidayu_config_phone_bind'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_EDIT'=>array(
		'title'=>lang('alidayu_config_phone_edit'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_FOTGET'=>array(
		'title'=>lang('alidayu_config_phone_fotget'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_FOTGET_PAY'=>array(
		'title'=>lang('alidayu_config_phone_fotget_pay'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_SHOP_OPEN_SUCCESS'=>array(
		'title'=>lang('alidayu_config_phone_user_shop_open_success'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_OPEN_FAIL'=>array(
		'title'=>lang('alidayu_config_phone_shop_open_fail'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_CONSUME_VERFIY'=>array(
		'title'=>lang('alidayu_config_phone_user_consume_verfiy'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_ORDER_VERIFICATCODE'=>array(
		'title'=>lang('alidayu_config_phone_user_order_verificatcode'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_ORDER_VERIFICAT'=>array(
		'title'=>lang('alidayu_config_phone_user_order_verificat'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_COMMON_VERFIY'=>array(
		'title'=>lang('alidayu_config_phone_common_verfiy'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'warn_shop'=>array(
		'title'=>'<span style="color:blue;font-size:18px;padding-top:10px">'.lang('alidayu_config_warn_shop').'</span>',
		'type'=>'hidden',
		'value'=>''
	),
	'PHONE_SHOP_SUBMIT_ORDER'=>array(
		'title'=>lang('alidayu_config_phone_shop_submit_order'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_PAY_ORDER'=>array(
		'title'=>lang('alidayu_config_phone_shop_pay_order'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_CANCEL_ORDER'=>array(
		'title'=>lang('alidayu_config_phone_shop_cancel_order'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_REJECT_ORDER'=>array(
		'title'=>lang('alidayu_config_phone_shop_reject_order'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'warn_admin'=>array(
		'title'=>'<span style="color:blue;font-size:18px;padding-top:10px">'.lang('alidayu_config_warn_admin').'</span>',
		'type'=>'hidden',
		'value'=>''
	),
	'PHONE_ADMIN_REFUND_ORDER'=>array(
		'title'=>lang('alidayu_config_phone_admin_refund_order'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_ADMIN_COMPLAINT_ORDER'=>array(
		'title'=>lang('alidayu_config_phone_admin_complaint_order'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_ADMIN_CASH_DRAWS'=>array(
		'title'=>lang('alidayu_config_phone_admin_cash_draws'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	)
);
