<?php
return array(
	'warn'=>array(
		'title'=>'<span style="color:red;font-size:20px;">'.lang('dysms_config1').'</span>',
		'type'=>'hidden',
		'value'=>''
	),
	'smsKey'=>array(
		'title'=>'Access Key ID<span style="color:#FF6666;">'.lang('dysms_config2'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'smsPass'=>array(
		'title'=>'Access Key Secret',
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'signature'=>array(
		'title'=>lang('dysms_config3'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_REGISTER_VERFIY'=>array(
		'title'=>lang('dysms_config4'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_BIND'=>array(
		'title'=>lang('dysms_config5'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_EDIT'=>array(
		'title'=>lang('dysms_config6'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_FOTGET'=>array(
		'title'=>lang('dysms_config7'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_FOTGET_PAY'=>array(
		'title'=>lang('dysms_config8'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_SHOP_OPEN_SUCCESS'=>array(
		'title'=>lang('dysms_config9'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_OPEN_FAIL'=>array(
		'title'=>lang('dysms_config10'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_CONSUME_VERFIY'=>array(
		'title'=>lang('dysms_config11'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_ORDER_VERIFICATCODE'=>array(
		'title'=>lang('dysms_config12'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_USER_ORDER_VERIFICAT'=>array(
		'title'=>lang('dysms_config13'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_COMMON_VERFIY'=>array(
		'title'=>lang('dysms_config15'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'warn_shop'=>array(
		'title'=>lang('dysms_config16'),
		'type'=>'hidden',
		'value'=>''
	),
	'PHONE_SHOP_SUBMIT_ORDER'=>array(
		'title'=>lang('dysms_config17'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_PAY_ORDER'=>array(
		'title'=>lang('dysms_config18'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_CANCEL_ORDER'=>array(
		'title'=>lang('dysms_config19'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_SHOP_REJECT_ORDER'=>array(
		'title'=>lang('dysms_config20'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'warn_admin'=>array(
		'title'=>lang('dysms_config21'),
		'type'=>'hidden',
		'value'=>''
	),
	'PHONE_ADMIN_REFUND_ORDER'=>array(
		'title'=>lang('dysms_config22'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_ADMIN_COMPLAINT_ORDER'=>array(
		'title'=>lang('dysms_config23'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	),
	'PHONE_ADMIN_CASH_DRAWS'=>array(
		'title'=>lang('dysms_config24'),
		'type'=>'text',
		'value'=>'',
		'tips'=>''
	)
);
